### ISSUE TITLE
Name TextField Error

### ISSUE THREAD

**Issue by mrmayurgithub** [gskinnerTeam/flutter-folio#1]
When trying to fill in the first name and the last name in the TextField, the user is unable to write the name in one go. 
For example, the user has to do something like this, first enter a letter and then again press the textfield to focus on it, then again enter another letter. This causes a bad user experience.
![Screenshot from 2021-03-04 00-12-23](https://user-images.githubusercontent.com/58694295/109855478-5349c880-7c7e-11eb-92e0-67f913de7938.png)

**Comment by esDotDev** [comment]
This is a known issue and we have a fixed incoming. Thanks!

**Comment by esDotDev** [comment]
dupe https://github.com/gskinnerTeam/flutter-folio/issues/3
