### ISSUE TITLE
text partially hidden (web app)

### ISSUE THREAD

**Issue by wugulabs** [gskinnerTeam/flutter-folio#13]
'Add description' is partly hidden.
Can not be resolved by increasing browser window size.

![image](https://user-images.githubusercontent.com/47014723/109931209-d98afc80-7cc8-11eb-8858-ca056bc331fd.png)

**Comment by esDotDev** [comment]
This is fixed in the latest version, 1.1.2, thanks for the report! Please re-open if you can still reproduce.
