### ISSUE TITLE
Linux build error

### ISSUE THREAD

**Issue by ingmferrer** [gskinnerTeam/flutter-folio#2]
✘ abc@xyz  ~/Downloads/linux_build/bundle  ./flutter_folio
flutter: firestore-DART Initialized
flutter: Bootstrap Started, v1.0.0-RC6
flutter: Loading file @ /home/abc/.local/share/flutterfolio/app-model
flutter: FileSystemException: Cannot open file, path = '/home/abc/.local/share/flutterfolio/app-model' (OS Error: No such file or directory, errno = 2)
flutter: Failed to decode save file json: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
flutter: File loaded, Rect.fromLTRB(0.0, 0.0, 0.0, 0.0)
flutter: Invalid argument(s): Failed to load dynamic library (libgtk-3.so: cannot open shared object file: No such file or directory)
flutter: #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
flutter: #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20)
flutter: #2      _libgtk (package:bitsdojo_window_linux/src/gtk.dart:5)
flutter: #3      gtkWindowIsMaximized (package:bitsdojo_window_linux/src/gtk.dart)
flutter: #4      GtkWindow.isMaximized (package:bitsdojo_window_linux/src/window.dart)
flutter: #5      LinuxTitleBar.build (package:flutter_folio/_utils/native_window_utils/titlebar_wrappers/linux_title_bar.dart:39)
flutter: #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4661)
flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4587)
flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3623)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3378)
flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4566)
flutter: #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561)
flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3623)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3378)
flutter: #19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5653)
flutter: #20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #34     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #38     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #41     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #42     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #44     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5595)
flutter: #45     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #48     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #49     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #50     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #53     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #59     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #65     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6073)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #71     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #72     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #76     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #77     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #81     ProxyElement.update (package:flutter/src/widgets/framework.dart:4935)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4759)
flutter: #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:4791)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #88     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5595)
flutter: #89     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6197)
flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #93     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:4281)
flutter: #97     StatelessElement.update (package:flutter/src/widgets/framework.dart:4668)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:3365)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4612)
^C
 ✘ abc@xyz  ~/Downloads/linux_build/bundle  

I'm using ubuntu 20.04.

Where can I find the missing file?

**Comment by esDotDev** [comment]
Thanks, we are working on a fix for this, we ran into some last minute issues due to some package conflicts with dart ffi.

**Comment by cenomla** [comment]
@ingmferrer what distro/environment are you running?

**Comment by cenomla** [comment]
Fixed, there was an issue in a package we depend on that referenced the wrong `libgtk-3.0.so` symlink.

**Comment by ingmferrer** [comment]
Can I download this fixed version?

**Comment by cenomla** [comment]
Yup, the latest Linux build includes this fix

**Comment by ingmferrer** [comment]
Now it run but when I type my email it writes the characters in other order.

checkout the video: https://www.dropbox.com/s/ncaljju2durfl8v/Screencast%20from%2003-03-21%2016%3A22%3A30.webm?dl=0

**Comment by mohammadrony** [comment]
When entering first name and last name it also writes the characters in different order.

**Comment by esDotDev** [comment]
Thanks, this is a known issue: https://github.com/flutter/flutter/issues/76474

We have a local fix pending which should work around it for now.

**Comment by iapicca** [comment]
here is some logs
<details>
<summary>doctor</summary>

```console
[✓] Flutter (Channel master, 2.1.0-11.0.pre.206, on Linux, locale en_US.UTF-8)
    • Flutter version 2.1.0-11.0.pre.206 at /home/francesco/snap/flutter/common/flutter
    • Framework revision bc9d0e0a4b (4 hours ago), 2021-03-11 17:25:02 +0530
    • Engine revision 1b68503bc8
    • Dart version 2.13.0 (build 2.13.0-125.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /home/francesco/Android/Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = /home/francesco/Android/Sdk
    • Java binary at: /usr/lib/jvm/java-1.8.0-openjdk-amd64/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_282-8u282-b08-0ubuntu1~20.04-b08)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • CHROME_EXECUTABLE = /snap/bin/chromium

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[✓] Connected device (2 available)
    • Linux (desktop) • linux  • linux-x64      • Linux
    • Chrome (web)    • chrome • web-javascript • Chromium 89.0.4389.82 snap

! Doctor found issues in 1 category.

```

</details>

<details>
<summary>neofetch</summary>

```console
            .-/+oossssoo+/-.               francesco@francesco-yoga720 
        `:+ssssssssssssssssss+:`           --------------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: 80X6 Lenovo YOGA 720-13IKB 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.8.0-44-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 2 hours, 26 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1777 (dpkg), 6 (flatpak), 33 (snap) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: GNOME 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Adwaita 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Yaru-dark [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Yaru [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Terminal: gnome-terminal 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      CPU: Intel i5-7200U (4) @ 2.500GHz 
    .ossssssssssssssssssdMMMNysssso.       GPU: Intel HD Graphics 620 
      -+sssssssssssssssssyyyssss+-         Memory: 5466MiB / 7685MiB 
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.                                       
                                                                   
```

</details>



<details>
<summary>logs</summary>
```bash
Launching lib/main.dart on Linux in release mode...
Building Linux application...                                           

Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
flutter: firestore-DART Initialized
flutter: Bootstrap Started, v1.1.3
flutter: Loading file @ /home/francesco/.local/share/flutterfolio/app-model
flutter: FileSystemException: Cannot open file, path = '/home/francesco/.local/share/flutterfolio/app-model' (OS Error: No such file or directory, errno = 2)
flutter: Failed to decode save file json: NoSuchMethodError: The getter 'length' was called on null.
Receiver: null
Tried calling: length
flutter: File loaded, Rect.fromLTRB(0.0, 0.0, 0.0, 0.0)
flutter: Invalid argument(s): Failed to load dynamic library 'libgtk-3.so': libgtk-3.so: cannot open shared object file: No such file or directory
flutter: #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11)
flutter: #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20)
flutter: #2      _libgtk (package:bitsdojo_window_linux/src/gtk.dart:4)
flutter: #3      gtkWindowIsMaximized (package:bitsdojo_window_linux/src/gtk.dart)
flutter: #4      GtkWindow.isMaximized (package:bitsdojo_window_linux/src/window.dart)
flutter: #5      LinuxTitleBar.build (package:flutter_folio/_utils/native_window_utils/titlebar_wrappers/linux_title_bar.dart:39)
flutter: #6      StatelessElement.build (package:flutter/src/widgets/framework.dart:4640)
flutter: #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4566)
flutter: #8      Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #9      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4545)
flutter: #10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4540)
flutter: #11     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3603)
flutter: #12     Element.updateChild (package:flutter/src/widgets/framework.dart:3358)
flutter: #13     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #14     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #15     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4545)
flutter: #16     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4540)
flutter: #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3603)
flutter: #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3358)
flutter: #19     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5636)
flutter: #20     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6180)
flutter: #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #23     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #24     ProxyElement.update (package:flutter/src/widgets/framework.dart:4914)
flutter: #25     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #26     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6056)
flutter: #27     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #28     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #29     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #30     StatelessElement.update (package:flutter/src/widgets/framework.dart:4647)
flutter: #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #33     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #34     StatelessElement.update (package:flutter/src/widgets/framework.dart:4647)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #37     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #38     ProxyElement.update (package:flutter/src/widgets/framework.dart:4914)
flutter: #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #41     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #42     ProxyElement.update (package:flutter/src/widgets/framework.dart:4914)
flutter: #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #44     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5578)
flutter: #45     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6180)
flutter: #46     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #47     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #48     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4738)
flutter: #49     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #50     StatefulElement.update (package:flutter/src/widgets/framework.dart:4770)
flutter: #51     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #53     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #54     ProxyElement.update (package:flutter/src/widgets/framework.dart:4914)
flutter: #55     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #56     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #57     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4738)
flutter: #58     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #59     StatefulElement.update (package:flutter/src/widgets/framework.dart:4770)
flutter: #60     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #61     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6056)
flutter: #62     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #63     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #64     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #65     StatelessElement.update (package:flutter/src/widgets/framework.dart:4647)
flutter: #66     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #67     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6056)
flutter: #68     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4738)
flutter: #71     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #72     StatefulElement.update (package:flutter/src/widgets/framework.dart:4770)
flutter: #73     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #75     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4738)
flutter: #76     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #77     StatefulElement.update (package:flutter/src/widgets/framework.dart:4770)
flutter: #78     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #79     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #80     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #81     ProxyElement.update (package:flutter/src/widgets/framework.dart:4914)
flutter: #82     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4738)
flutter: #85     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #86     StatefulElement.update (package:flutter/src/widgets/framework.dart:4770)
flutter: #87     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #88     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5578)
flutter: #89     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6180)
flutter: #90     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #91     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #92     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #93     StatelessElement.update (package:flutter/src/widgets/framework.dart:4647)
flutter: #94     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)
flutter: #96     Element.rebuild (package:flutter/src/widgets/framework.dart:4260)
flutter: #97     StatelessElement.update (package:flutter/src/widgets/framework.dart:4647)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:3345)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4591)

```
</details>
