### ISSUE TITLE
Exit application on login screen?

### ISSUE THREAD

**Issue by tofanelli** [gskinnerTeam/flutter-folio#20]
is this should be here? 
![Screen Shot 2021-03-04 at 23 42 20](https://user-images.githubusercontent.com/5512922/110059646-62df1500-7d43-11eb-9813-2bd329e8a409.png)

steps
- go to - https://www.flutterfolio.com/builds/latest/web-build-auto/#/?
- on this gray area, right click

Cheers =)

**Comment by esDotDev** [comment]
It is meant to be in the Desktop builds, just not Web :) Thanks!

**Comment by esDotDev** [comment]
This is fixed in the latest version, 1.1.2, thanks for the report! Please re-open if you can still reproduce.
