### ISSUE TITLE
Takes additional tap to show keyboard on iPhone in web version. 

### ISSUE THREAD

**Issue by delay** [gskinnerTeam/flutter-folio#26]
The first tap focuses a textfield you can see the cursor becomes active. The second tap brings up the keyboard. I have noticed this problem in my own flutter web app.  See attached video. This is browsing the web version of the app on iOS.  

I would expect the first tap where the form field gets focus and the cursor blinks to bring up the keyboard.

https://user-images.githubusercontent.com/638246/110120257-6d6ccf00-7d82-11eb-9afa-8dd35c0b5cbe.mov

**Comment by esDotDev** [comment]
Could you please log this here with a minimal reproduction case? 
https://github.com/flutter/flutter/issues/

If you are able to reproduce it in your own code, it is likely not an issue with the app, but we'd love to track this issue against the main one.

**Comment by delay** [comment]
I will add it once I am working on a web version of my flutter app again.  I am currently working on another project.  If I have some free time I will try to make a reproduction.
