### ISSUE TITLE
Image picker is not working when using flutter folio website form windows: 

### ISSUE THREAD

**Issue by Satyam953** [gskinnerTeam/flutter-folio#29]
I am using windows 10 and using your flutter folio website from the chrome browser.

when I tap the image button an empty container(with delete and add to page) button comes up that does nothing.

          'Yes I know that flutter folio is just a demonstration to 
                   show that one can develop projects for one of the  platform"

all I wanted is to let you know.!

**Comment by esDotDev** [comment]
This is fixed in the latest version, 1.1.2, thanks for the report! Please re-open if you can still reproduce.
