### ISSUE TITLE
Duplicate static functions in _utils

### ISSUE THREAD

**Issue by AdrianSima** [gskinnerTeam/flutter-folio#38]
There's the `input_utils.dart` with the `InputUtils` class that has 3 static functions: **hideKeyboard()**, **isMouseConnected()** and **unFocus()** and then there is another file: `utils.dart` that has the class `Utils` that has the same 3 static functions plus another one: **benchmark(String name, Function() test)**.

Is there a reason why these are duplicated like this?

**Comment by esDotDev** [comment]
Just an oversight, thanks!
