### ISSUE TITLE
No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()

### ISSUE THREAD

**Issue by sibylantoninobajeli** [gskinnerTeam/flutter-folio#39]
I get the the following error

**_"No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()"_**

**This if my system configuration:**

doctor --verbose
[√] Flutter (Channel stable, 2.0.1, on Microsoft Windows [Versione 10.0.19042.867], locale it-IT)
    • Flutter version 2.0.1 at C:\flutter
    • Framework revision c5a4b4029c (7 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Admin1\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 89.0.4389.82
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 84.0.522.73

! Doctor found issues in 1 category.
Process finished with exit code 0

**Comment by esDotDev** [comment]
This is fixed on master, please re-open if you're still having issues.
