### ISSUE TITLE
Windows 10 run error

### ISSUE THREAD

**Issue by wstrunk** [gskinnerTeam/flutter-folio#40]
I downloaded the Wondows version from https://flutter.gskinner.com/#g-download
When I run the program an enter an email address in the registration dialog, the complete keyboard is not useable as soon as I type the @ Character.
It feels like SHIFT and ALT are permantently pressed as with the CAPS-Lock key.

**Comment by esDotDev** [comment]
I think this is a dupe, we can not reproduce here. Are you using a non-english keyboard by chance?
https://github.com/gskinnerTeam/flutter-folio/issues/3

**Comment by wstrunk** [comment]
Sorry for answering that late. I use a German keyboard layout.
