### ISSUE TITLE
Camera access on iOS

### ISSUE THREAD

**Issue by Kei-z** [gskinnerTeam/flutter-folio#42]
with iPhone SE (2nd), iOS 14.4

When I tried add pictures and accessed its device camera, app was crashed with this log:

> [access] This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSPhotoLibraryUsageDescription key with a string value explaining to the user how the app uses this data.

**Comment by esDotDev** [comment]
Thanks, just should be fixed now, please let us know if not.
Cheers,
