### ISSUE TITLE
Can we have a discussion tab in the Github repo?

### ISSUE THREAD

**Issue by zyllus17** [gskinnerTeam/flutter-folio#49]
I came across this project and I have been working with Flutter for a year but after seeing this project, I feel overwhelmed after seeing so much stuff that I have no idea what it is. I would not like to clutter the issue section with my questions and since Github has a new discussion feature, I can ask all my silly questions there and it will help new-comers to this project as well to find answers.

**Comment by esDotDev** [comment]
Done, thanks for the heads up
