### ISSUE TITLE
Profile form loses focus while typing

### ISSUE THREAD

**Issue by malkia** [gskinnerTeam/flutter-folio#6]
While typing my name, after each click the web app loses focus, and have to click back. It doesn't happen when I'm editing text with the app.

![image](https://user-images.githubusercontent.com/51738/109867329-392ace80-7c1b-11eb-9f12-ec87a9ef7840.png)

**Comment by esDotDev** [comment]
dupe https://github.com/gskinnerTeam/flutter-folio/issues/3
