### ISSUE TITLE
`First Name` and `Last Name` TextField lose focus after each type

### ISSUE THREAD

**Issue by nogicoder** [gskinnerTeam/flutter-folio#8]
I have to update the name by a character type follow with a mouse click for every character. Demonstration below:
Operating system: Windows 10 Pro 64-bit (10.0, Build 19041)

https://user-images.githubusercontent.com/43837352/109900351-cfb5c900-7cc9-11eb-96ea-ab16b715726c.mp4

**Comment by wugulabs** [comment]
This issue also occurs in the Windows build.

**Comment by esDotDev** [comment]
This is fixed in the latest version, 1.1.2, thanks for the report! Please re-open if you can still reproduce.
